# Generated by roxytest: do not edit by hand!

# File R/"02-run.R": @testexamples

test_that("Function run() @ L24", {
  
  x <- prepare(
    data = mtcars,
    vars_y = "mpg",
    vars_x = c("factor(cyl)", colnames(mtcars)[3:5]),
    vars_c = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  x = x |> run()
  x
  is(x, "REGObject")
})

