# Generated by roxytest: do not edit by hand!

# File R/"00-class.R": @testexamples

test_that("[unknown alias] @ L35", {
  
  x <- REGObject(
    data = mtcars,
    vars_y = "mpg",
    vars_x = c("factor(cyl)", colnames(mtcars)[3:5]),
    vars_c = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  x
  is(x, "REGObject")
})

