# Generated by roxytest: do not edit by hand!

# File R/REGModelList.R: @testexamples

test_that("Function REGModelList() @ L56", {
  
  # GLM regression
  ml <- REGModelList$new(
    data = mtcars,
    y = "mpg",
    x = c("factor(cyl)", colnames(mtcars)[3:5]),
    covars = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  ml
  ml$print()
  ml$plot_forest()
  
  ml$build(f = "gaussian")
  
  ml$print()
  ml$result
  ml$forest_data
  ml$plot_forest()
  
  lung <- survival::lung
  # Cox-PH regression
  ml2 <- REGModelList$new(
    data = lung,
    y = c("time", "status"),
    x = c("age", "ph.ecog", "ph.karno"),
    covars = c("factor(sex)")
  )
  ml2$build()
  ml2$plot_forest()
  ml2$plot_connected_risk()
  
  # Group Cox analysis
  lung$ph.ecog <- factor(lung$ph.ecog)
  ml3 <- REGModelList$new(
    data = lung,
    y = c("time", "status"),
    x = c("ph.ecog"),
    covars = "age", group = "sex"
  )
  ml3$build()
  ml3$plot_forest()
  
  expect_s3_class(ml, "REGModelList")
  expect_s3_class(ml2, "REGModelList")
  expect_s3_class(ml3, "REGModelList")
})

