# Generated by roxytest: do not edit by hand!

# File R/REGModelList.R: @testexamples

test_that("Function REGModelList() @ L40", {
  
  # GLM regression
  ml <- REGModelList$new(
    data = mtcars,
    y = "mpg",
    x = c("factor(cyl)", colnames(mtcars)[3:5]),
    covars = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  ml
  ml$print()
  ml$plot_forest()
  
  ml$build(f = "gaussian")
  
  ml$print()
  ml$result
  ml$forest_data
  ml$plot_forest()
  
  # Cox-PH regression
  ml2 <- REGModelList$new(
    data = survival::lung,
    y = c("time", "status"),
    x = c("age", "ph.ecog", "ph.karno"),
    covars = c("factor(sex)")
  )
  ml2$build()
  
  expect_s3_class(ml, "REGModelList")
})

